from distutils.core import setup

setup(name='Nib',
      description='Static Site Generator',
      version='0.1',
      author='John Reese',
      author_email='john@noswap.com',
      url='https://github.com/jreese/nib',
      classifiers=['License :: OSI Approved :: MIT License',
                   'Operating System :: OS Independent',
                   'Programming Language :: Python',
                   'Programming Language :: Python :: 3',
                   'Topic :: Utilities',
                   'Development Status :: 2 - Pre-Alpha',
                   ],
      license='MIT License',
      requires=['sh (>=1.0)',
                'Jinja2 (>=2.6)',
                'Marjkdown (>=2.2.0)',
                'PyYAML (>=3.10)',
                ],
      packages=['nib', 'nib.plugins'],
      package_data={'nib': ['config.defaults']},
      scripts=['bin/nib'],
      )
